package io.legado.app.domain.usecase.structured

import com.google.gson.JsonObject
import io.legado.app.data.entities.AiPromptTemplate
import io.legado.app.data.entities.AiToolConfig
import io.legado.app.domain.gateway.AiChatGateway
import io.legado.app.domain.gateway.AiProfileGateway
import io.legado.app.domain.gateway.AiPromptTemplateGateway
import io.legado.app.domain.gateway.AiTextGateway
import io.legado.app.domain.gateway.AiToolConfigGateway
import io.legado.app.domain.model.AiCallMeta
import io.legado.app.domain.model.AiCallSource
import io.legado.app.domain.model.AiGenerateRequest
import io.legado.app.domain.model.AiGenerationParams
import io.legado.app.domain.model.AiModelConfig
import io.legado.app.domain.model.AiProviderConfig
import io.legado.app.domain.model.AiTaskType
import io.legado.app.domain.model.UserCardPatch
import io.legado.app.domain.usecase.ai.resolvedSubModelProfileId
import io.legado.app.utils.GSON

class UserCardMutator(
    private val aiChatGateway: AiChatGateway,
    private val aiProfileGateway: AiProfileGateway,
    private val aiTextGateway: AiTextGateway,
    private val promptTemplateGateway: AiPromptTemplateGateway,
    private val toolConfigGateway: AiToolConfigGateway,
) {
    data class PatchResult(
        val success: Boolean,
        val message: String,
        val conversationId: String = "",
        val changes: List<FieldChange> = emptyList(),
        val data: Map<String, Any?> = emptyMap(),
    )

    suspend fun read(conversationId: String?): String {
        val convId = conversationId?.takeIf { it.isNotBlank() }
            ?: return """{"error":"conversationId is required"}"""
        val conv = aiChatGateway.getConversation(convId)
            ?: return """{"error":"Conversation not found: $convId"}"""
        return GSON.toJson(
            mapOf(
                "conversationId" to conv.id,
                "userName" to conv.userName,
                "userDescription" to conv.userDescription,
                "enabled" to conv.userCardEnabled,
            )
        )
    }

    suspend fun previewPatch(patch: UserCardPatch): List<FieldChange> {
        if (patch.generate) {
            return listOf(FieldChange("ai_generate", "", "User persona will be generated by AI"))
        }
        val convId = patch.conversationId?.takeIf { it.isNotBlank() }
            ?: return listOf(FieldChange("conversationId", "", "Conversation required"))
        val existing = aiChatGateway.getConversation(convId)
        val oldFields = mapOf(
            "userName" to (existing?.userName.orEmpty()),
            "userDescription" to (existing?.userDescription.orEmpty()),
            "enabled" to (existing?.userCardEnabled?.toString().orEmpty()),
        )
        val newFields = mapOf(
            "userName" to (patch.name ?: oldFields["userName"].orEmpty()),
            "userDescription" to (patch.description ?: oldFields["userDescription"].orEmpty()),
            "enabled" to (patch.enabled?.toString() ?: oldFields["enabled"].orEmpty()),
        )
        return StructuredDataDiff.diffFields(oldFields, newFields)
    }

    suspend fun applyPatch(patch: UserCardPatch): PatchResult {
        if (patch.generate) return generateFromConversation(patch)
        val convId = patch.conversationId?.takeIf { it.isNotBlank() }
            ?: return PatchResult(false, "conversationId is required")
        val existing = aiChatGateway.getConversation(convId)
            ?: return PatchResult(false, "Conversation not found: $convId")
        val changes = previewPatch(patch)
        val hasField = patch.name != null || patch.description != null || patch.enabled != null
        if (!hasField) {
            return PatchResult(false, "No fields to patch")
        }
        val userName = patch.name?.trim() ?: existing.userName
        val userDescription = patch.description?.trim() ?: existing.userDescription
        val enabled = patch.enabled ?: existing.userCardEnabled
        aiChatGateway.updateConversationUserCard(convId, userName, userDescription, enabled)
        return PatchResult(
            success = true,
            message = "User persona updated",
            conversationId = convId,
            changes = changes,
            data = mapOf(
                "conversationId" to convId,
                "userName" to userName,
                "userDescription" to userDescription,
                "enabled" to enabled,
            ),
        )
    }

    private suspend fun generateFromConversation(patch: UserCardPatch): PatchResult {
        val convId = patch.conversationId?.takeIf { it.isNotBlank() }
            ?: return PatchResult(false, "conversationId is required")
        val messagesText = aiChatGateway.getMessagesForRegeneration(convId).joinToString("\n\n") { msg ->
            "[${if (msg.first == "user") "用户" else "助手"}] ${msg.second.take(2000)}"
        }
        val existing = aiChatGateway.getConversation(convId)
        val existingHint = existing?.let { conv ->
            if (conv.userName.isBlank() && conv.userDescription.isBlank()) {
                ""
            } else {
                "\n\n## 当前用户描述（请在此基础上更新）\n称呼：${conv.userName}\n描述：${conv.userDescription}"
            }
        }.orEmpty()
        val prompt = promptTemplateGateway.getPrompt(AiPromptTemplate.GENERATE_USER_CARD_PROMPT)
        val system = io.legado.app.domain.usecase.ai.PromptRoleSplit.stripPlaceholders(prompt)
        val user = buildString {
            if (messagesText.isNotBlank()) append(messagesText)
            if (existingHint.isNotBlank()) {
                if (isNotEmpty()) append("\n")
                append(existingHint.trimStart())
            }
            if (!patch.hint.isNullOrBlank()) {
                if (isNotEmpty()) append("\n\n")
                append("## Extra Guidance\n").append(patch.hint)
            }
        }.ifBlank { "（无对话记录）" }

        val config = toolConfigGateway.getByToolName("patch_user_card")
        val result = generateWithConfig(system, user, config)
        return result.fold(
            onSuccess = { response ->
                val jsonStr = extractJsonObject(response.text)
                runCatching {
                    val obj = GSON.fromJson(jsonStr, JsonObject::class.java)
                    val userName = obj.get("userName")?.asString?.trim().orEmpty()
                    val userDescription = obj.get("description")?.asString?.trim().orEmpty()
                    val enabled = obj.get("enabled")?.asBoolean ?: true
                    aiChatGateway.updateConversationUserCard(convId, userName, userDescription, enabled)
                    PatchResult(
                        success = true,
                        message = "User persona generated",
                        conversationId = convId,
                        changes = listOf(FieldChange("userName", existing?.userName.orEmpty(), userName)),
                        data = mapOf(
                            "conversationId" to convId,
                            "userName" to userName,
                            "userDescription" to userDescription,
                            "enabled" to enabled,
                        ),
                    )
                }.getOrElse { PatchResult(false, "Failed to parse AI response: ${it.message}") }
            },
            onFailure = { PatchResult(false, "AI generation failed: ${it.message}") }
        )
    }

    private suspend fun generateWithConfig(
        systemPrompt: String,
        userPrompt: String,
        config: AiToolConfig?,
    ): Result<io.legado.app.domain.model.AiGenerateResponse> {
        val subModelId = config.resolvedSubModelProfileId(aiProfileGateway)
        val messages = io.legado.app.domain.usecase.ai.PromptRoleSplit.messages(systemPrompt, userPrompt)
        return if (subModelId != null) {
            val modelProfile = aiProfileGateway.getModel(subModelId)
                ?: return Result.failure(IllegalStateException("Sub-model not found"))
            val provider = aiProfileGateway.getProvider(modelProfile.providerId)
                ?: return Result.failure(IllegalStateException("Provider not found"))
            aiTextGateway.generate(
                AiGenerateRequest(
                    model = modelProfile.toModelConfig(provider),
                    messages = messages,
                    params = AiGenerationParams(),
                    callMeta = AiCallMeta(AiCallSource.CHAT, null),
                )
            )
        } else {
            val preset = aiProfileGateway.getTaskPreset(AiTaskType.CHAT)
                ?: return Result.failure(IllegalStateException("No chat model configured"))
            aiTextGateway.generate(
                AiGenerateRequest(
                    model = preset.model,
                    messages = messages,
                    params = preset.params,
                    callMeta = AiCallMeta(AiCallSource.CHAT, null),
                )
            )
        }
    }

    private fun extractJsonObject(text: String): String {
        var t = text.trim().replace(Regex("""```(?:json)?\s*"""), "").replace(Regex("""\s*```"""), "").trim()
        val start = t.indexOf('{')
        var depth = 0
        var end = -1
        for (i in start until t.length) {
            when (t[i]) {
                '{' -> depth++
                '}' -> { depth--; if (depth == 0) { end = i; break } }
            }
        }
        return if (start >= 0 && end > start) t.substring(start, end + 1) else t
    }

    private fun io.legado.app.data.entities.AiModelProfile.toModelConfig(provider: io.legado.app.data.entities.AiProviderProfile) =
        AiModelConfig(
            id = id,
            provider = AiProviderConfig(
                id = provider.id, name = provider.name, protocol = provider.protocol,
                baseUrl = provider.baseUrl, apiKey = provider.apiKey, modelsUrl = provider.modelsUrl,
                chatPath = provider.chatPath ?: "/chat/completions",
                responsesPath = provider.responsesPath ?: "/responses",
                messagesPath = provider.messagesPath ?: "/v1/messages",
                modelsPath = provider.modelsPath,
                headers = emptyMap(), customHeaders = emptyMap(),
            ),
            displayName = displayName, modelId = modelId,
            contextWindow = contextWindow, maxOutputTokens = maxOutputTokens,
        )
}
